# Generated by Django 2.1.1 on 2020-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200602_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restriction',
            field=models.CharField(choices=[('restricted', 'Restricted'), ('public', 'Public')], default='restricted', max_length=10),
        ),
    ]
